# Generated by Django 4.2 on 2023-05-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_friendrequest_friendlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendlist',
            options={'verbose_name': 'Friend List', 'verbose_name_plural': 'Friends List'},
        ),
        migrations.AlterModelTable(
            name='friendlist',
            table='friends_friend_list',
        ),
    ]
