# Generated by Django 4.2 on 2023-05-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_friendlist_options_alter_friendlist_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'Friend Request', 'verbose_name_plural': 'Friend Requests'},
        ),
        migrations.AlterModelTable(
            name='friendrequest',
            table='friends_friend_request',
        ),
    ]
