# Generated by Django 4.2 on 2023-05-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_share_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='share',
            unique_together=set(),
        ),
    ]
