# Generated by Django 4.2 on 2023-05-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_share_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users/images/defaultavatar.png', upload_to='users/images', verbose_name='Image'),
        ),
    ]
