# Generated by Django 4.2 on 2023-05-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users/images/defaultavatar.png', upload_to='users/images', verbose_name='Image'),
        ),
    ]
